#!/usr/bin/env zsh

# automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# translucent dock icons for hidden apps
defaults write com.apple.dock showhidden -bool true

# hide recent apps
defaults write com.apple.dock show-recents -bool false

# show all file extensions
defaults write -g AppleShowAllExtensions -bool true

# disable text correction
defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false
defaults write -g NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write -g NSAutomaticPeriodSubstitutionEnabled -bool false
defaults write -g NSAutomaticDashSubstitutionEnabled -bool false
defaults write -g NSAutomaticCapitalizationEnabled -bool false

# normal scroll direction
defaults write -g com.apple.swipescrolldirection -bool true 

# hide scroll bars even if an external mouse is connected
defaults write -g AppleShowScrollBars -string "WhenScrolling"
